/* Links importantes da operação do Fluxo. Agrupados pelo momento em que
   se usa: recorrente (dia a dia), evento, integração, canais do Slack,
   ferramentas. Só entra aqui o que NÃO é projeto do time: o que o time
   construiu mora na aba "Projetos e agentes" (dados/projetos.js e agentes.js).
   Fonte: mensagens no Slack (ver DECISOES.md). */

const GRUPOS_LINKS = ['Recorrentes', 'Eventos', 'Integração e treinamento', 'Canais do Slack', 'Ferramentas'];

const LINKS = [
  /* ---------- Recorrentes ---------- */
  { id: 'fluxer', grupo: 'Recorrentes', nome: 'Fluxer', url: 'https://flx.vendatodosantodia.com.br', descricao: 'Plataforma do Fluxo: mentorados, planos de ação, análises, atendimento (WhatsApp), Academy e ferramentas.', obs: 'Login com o e-mail vtsd.' },
  { id: 'academy', grupo: 'Recorrentes', nome: 'Academy (aulas)', url: 'https://flx.vendatodosantodia.com.br/academy', descricao: 'Aulas de todos os cursos e módulos do Fluxo dentro do Fluxer.', obs: 'Para achar aula pelo conteúdo, use a Transcrição de todos os produtos.' },
  { id: 'zoom-semanal', grupo: 'Recorrentes', nome: 'Zoom semanal (tira-dúvidas e retiros)', url: 'https://vtsd.com.br/zoom-semanal', descricao: 'Link curto fixo do Zoom semanal; a URL de destino é trocada no Terminus a cada encontro.', obs: 'Link de Zoom nunca vai direto para o mentorado: sempre pelo Terminus.' },
  { id: 'live-semanal', grupo: 'Recorrentes', nome: 'Live semanal com o Leandro', url: 'https://vtsd.com.br/live-semanal-leandro', descricao: 'Perguntas e respostas ao vivo com o Leandro, para todos os mentorados.', obs: 'Chamar os mentorados com a dúvida já anotada.' },
  { id: 'zoom-duvidas', grupo: 'Recorrentes', nome: 'Zoom tira-dúvidas temático', url: 'https://vtsd.com.br/zoom-duvidas', descricao: 'Link curto usado nos zooms tira-dúvidas temáticos (ex.: Stories 10x).', obs: '' },
  { id: 'mandala360', grupo: 'Recorrentes', nome: 'Mandala 360', url: 'https://vtsd.com.br/mandala360', descricao: 'Encontro em que o time gira a Mandala ao vivo e cria ideias de anúncio para o mentorado.', obs: 'Só para mentorados da lista do bônus do plano de ação.' },
  { id: 'feedback', grupo: 'Recorrentes', nome: 'Formulário de feedback (eventos)', url: 'https://vtsd.com.br/feedback', descricao: 'Formulário padrão de feedback dos zooms e retiros; os materiais ficam no final dele.', obs: 'Depois do evento, mande o link do feedback e não o da pasta.' },
  { id: 'feedback-mandala', grupo: 'Recorrentes', nome: 'Feedback da Mandala 360', url: 'https://vtsd.com.br/feedback-mandala360', descricao: 'Formulário de feedback específico da Mandala 360.', obs: '' },
  { id: 'monday-links', grupo: 'Recorrentes', nome: 'Monday: Central de Links da Mentoria', url: 'https://venda-todo-santo-dia.monday.com/boards/2061768785', descricao: 'Quadro com os links de materiais de todos os eventos (Materiais Eventos > evento > pastinha).', obs: '' },
  { id: 'monday-renovacao', grupo: 'Recorrentes', nome: 'Monday: contratos de renovação', url: 'https://venda-todo-santo-dia.monday.com/boards/18420875498', descricao: 'Status dos contratos de renovação enviados aos mentorados (lembrar de assinar quem está como ENVIADO).', obs: '' },
  { id: 'central-eventos', grupo: 'Recorrentes', nome: 'Central de Gestão de Eventos', url: 'https://central-do-retiro.vercel.app/', descricao: 'Planejamento, ao vivo e pós-evento num lugar só: cronograma, escala, palestrantes, copys de WhatsApp e e-mail, links e pendências. Em uso no dia a dia desde o Retiro Levantamento de Caixa (sprint de 29/09/2026).', obs: 'Login individual enviado pela Ana no privado. Se der certo, vai para dentro do Fluxer.' },

  { id: 'playlist-exemplos', grupo: 'Recorrentes', nome: 'YouTube: playlist Exemplos que Inspiram', url: 'https://www.youtube.com/playlist?list=PLveVb6p7gA6XmY2j0jtrBsbEg1wxbC7TQ', descricao: 'Palestras e depoimentos dos mentorados (Exemplos que Inspiram), atualizada periodicamente pelo time de Eventos e Entregáveis.', obs: 'Vídeo que o mentorado removeu ou deixou privado não aparece.' },
  { id: 'playlist-concurso', grupo: 'Recorrentes', nome: 'YouTube: playlist Concurso de Resultado', url: 'https://www.youtube.com/playlist?list=PLPJdn1HJZ2nc', descricao: 'Vídeos dos desafios (Express, Jump Cat e outros). Desde 21/09/2026 o time de Eventos e Entregáveis sobe todo vídeo novo aqui.', obs: '' },
  { id: 'melhores-ads', grupo: 'Recorrentes', nome: 'Melhores anúncios de captação (Drive)', url: 'https://drive.google.com/drive/u/0/folders/1EFpx0v2VRLNVkxvMY1ope7zyGlxDq3M1', descricao: 'Primeira das 5 pastas de "nossos melhores ads" passadas pela Clara em 24/08/2026; as outras 4 estão na pergunta "Onde pedir criativos" do assistente.', obs: 'Dizer a fase e o objetivo (captação, remarketing ou ao vivo) antes de pedir mais.' },
  { id: 'planilha-patrimonio', grupo: 'Recorrentes', nome: 'Planilha de patrimônio (Filosofia Ladeira)', url: 'https://docs.google.com/spreadsheets/d/18AVsFejCWVs8C-vKisLkU0qmIuodML0p/edit', descricao: 'Planilha de patrimônio usada no Filosofia Ladeira, compartilhada pelo Robson.', obs: '' },

  /* ---------- Eventos ---------- */
  { id: 'materiais-flp', grupo: 'Eventos', nome: 'Materiais: Fórmula de Lançamento Pago (set/2026)', url: 'https://eventos.vtsd.com.br/evento/formula-de-lancamento-pago/', descricao: 'Página de materiais da imersão FLP (22 a 24/09): PDFs das palestras e skills das partes práticas.', obs: '' },
  { id: 'retiro-black', grupo: 'Eventos', nome: 'Retiro Ultra Black Friday (página)', url: 'https://retiro-ultra-black-friday.vercel.app/', descricao: 'Página do Retiro da Black, que aponta para o Academy; o cronograma e os zooms semanais estão no Academy desde 03/09/2026.', obs: 'A página antiga do retiro (versão com "-2026" no endereço) está desatualizada e não deve ser compartilhada. Feedback do retiro: tally.so/r/MeZy9E; por tema: GxO57z, xX8vok, b51vG7, PdZkyx, vG8K14.' },
  { id: 'retiro-black-rtg', grupo: 'Eventos', nome: 'Retiro Black Friday: pasta da RTG (cronograma e materiais)', url: 'https://drive.google.com/drive/folders/1G_95UepCWy_-VqzroYSeXW9e0KeW6-5l', descricao: 'Pasta compartilhada da RTG em Eventos > Retiro Black, com o cronograma e os materiais das aulas semanais.', obs: 'Documento do cronograma: docs.google.com/document/d/1N4AAzgd9apg8UKnSmgr2FHPgXHAqnsp06TVszLNH4Yo' },
  { id: 'retiro-black-drive', grupo: 'Eventos', nome: 'Retiro Black Friday: pasta de materiais', url: 'https://drive.google.com/drive/folders/1OIyL3mfOVvibUrHPuqTyOuDski8NVCTK', descricao: 'Materiais disponibilizados nas aulas do retiro.', obs: 'Mandar o feedback, não a pasta.' },
  { id: 'playbook-black', grupo: 'Eventos', nome: 'Playbook Black Friday (Vilas Boas)', url: 'https://playbook-black-friday.vercel.app/', descricao: 'Planejamento de datas da Black do mentorado.', obs: '' },
  { id: 'playbook-mid', grupo: 'Eventos', nome: 'Playbook Black Friday mid ticket (Felipe Matheus)', url: 'https://playbook-black-friday-mid-ticket.vercel.app/', descricao: 'Página da aula "Divulgação de produto mid para Black Friday" (10/09).', obs: '' },
  { id: 'materiais-spp-ago', grupo: 'Eventos', nome: 'Materiais: SPP com IA (ago/2026)', url: 'https://vtsd.com.br/materiais-spp-ago26', descricao: 'Página de materiais do Seu Produto Pronto com IA de agosto.', obs: 'Página alternativa: vendatodosantodia.com.br/evento/spp-com-ia-ago-2026' },
  { id: 'materiais-spp-ia', grupo: 'Eventos', nome: 'Materiais: SPP com IA (jul/2026)', url: 'https://vtsd.com.br/materiais-spp-ia', descricao: 'Skills e materiais do SPP de julho (ex.: Skill Ideias de produto).', obs: '' },
  { id: 'retiro-caixa', grupo: 'Eventos', nome: 'Retiro Levantamento de Caixa (08 e 09/10)', url: 'https://vtsd.com.br/retiro-levantamento-de-caixa', descricao: 'URL curta do evento, criada no Terminus.', obs: 'Gestão do evento em central-do-retiro.vercel.app' },
  { id: 'analisador-day', grupo: 'Eventos', nome: 'Analisador Day Online', url: 'https://vtsd.com.br/analisador-day-online', descricao: 'Zoom do Analisador Day (bônus de renovação do Fluxo Festival).', obs: 'Feedback: tally.so/r/VLW08v' },
  { id: 'editor-paginas', grupo: 'Eventos', nome: 'Editor das páginas de evento', url: 'https://rtg.vtsd.com.br/login', descricao: 'Onde as páginas de eventos.vtsd.com.br são criadas e editadas.', obs: 'Arquivos sobem em download.vtsd.com.br/admin. Login no 1Password.' },
  { id: 'tally-feedback-modelo', grupo: 'Eventos', nome: 'Tally: modelo de feedback', url: 'https://tally.so/r/MeZy9E', descricao: 'Formulário de feedback do Retiro Black para duplicar em novos eventos.', obs: 'Modelo de inscrição de desafio: tally.so/r/VLX88J' },
  { id: 'mapa-caixa10x', grupo: 'Eventos', nome: 'Mapa mental: Retiro Caixa 10x (pico pago)', url: 'https://www.mindmeister.com/app/map/3739866736?t=MWdPDeu7mH', descricao: 'Mapa mental do Retiro Caixa 10x, a referência de pico pago (produto de R$ 1 mil ou mais).', obs: '' },

  /* ---------- Integração e treinamento ---------- */
  { id: 'ppt-integracao', grupo: 'Integração e treinamento', nome: 'Apresentação da reunião de integração (Canva)', url: 'https://www.canva.com/design/DAHWOjnohqw/JiKGpncaF-XLgyKC6tiw0w/edit', descricao: 'Slides usados na reunião de integração dos mentorados novos, para apresentar ou consultar o que é falado.', obs: 'Editável: cuidado para não alterar sem combinar com a Ellen.' },
  { id: 'integracao-zoom', grupo: 'Integração e treinamento', nome: 'Reunião de integração (Zoom)', url: 'https://us06web.zoom.us/j/82597295248', descricao: 'Link da reunião de integração dos mentorados novos, caso o mentorado não veja no Fluxer.', obs: 'Sem horário fixo: o Robson publica a agenda (dia e hora) no #fluxo-comercial-duvidas e o link fica no Fluxer. Se não abrir, confirme com o Robson: em 06/2026 também circulou us06web.zoom.us/j/82593341298.' },
  { id: 'miro-entrada', grupo: 'Integração e treinamento', nome: 'Mapa mental: fluxo de entrada dos mentorados', url: 'https://miro.com/welcomeonboard/VEVOcEZYMk5XZVVQUFE0S2ZmQ01xMDB6SEhRQ09mN214U01rci9ERGdtOWkrTXo4UEFvWEdpZ3BXNTRHYzh4RWZhME94NWptK1JwSWNwN2hJU240eUY1K0dIRU9TVzltNjFodzdDL2MySDNIRUNORmNWZ1FGSUtmTlFOcElWdTJUb3BVU1JmRldSVm83WnNaWmpWNGlnPT0hdjE=?share_link_id=822519151250', descricao: 'Quadro "Fluxo de Entrada Pico do Fluxo", fixado pela Ellen em 17/08/2026 (o link antigo mostrava a versão velha).', obs: '' },
  { id: 'mapa-processos-navs', grupo: 'Integração e treinamento', nome: 'Mapa mental: processos da navegação', url: 'https://www.mindmeister.com/app/map/4060385316?t=qWJqTKoK5d', descricao: 'Mapa mental dos processos do time de navegação, compartilhado pela Jéssica em 04/08/2026.', obs: '' },
  { id: 'ppt-boas-vindas', grupo: 'Integração e treinamento', nome: 'Apresentação de Boas-vindas (Canva)', url: 'https://canva.link/ua6jlgcgtn7c7rj', descricao: 'Nova apresentação de boas-vindas aos mentorados, feita pela Manu em 24/09/2026.', obs: '' },
  { id: 'pop-terminus', grupo: 'Integração e treinamento', nome: 'POP 314: traqueamento de links na Terminus', url: 'https://docs.google.com/document/d/1JWXcjfTrWv3xxZDa_jUHyrMpMFlm-pgVN1N3YjeoWjA/edit', descricao: 'Passo a passo com prints para criar links curtos e UTMs (vale até o ponto 6).', obs: 'Presets de UTM: DC 107 (planilha).' },
  { id: 'dc-utm', grupo: 'Integração e treinamento', nome: 'DC 107: UTMs para traqueamento', url: 'https://docs.google.com/spreadsheets/d/1uqZF_wYMxpE3qV80ybvvYDUKpcHxU4eeP-mMi9aLAAk/edit', descricao: 'Planilha com os presets de UTM.', obs: '' },
  { id: 'pop-active', grupo: 'Integração e treinamento', nome: 'POP 212: enviar e-mails na ActiveCampaign', url: 'https://docs.google.com/document/d/1KTquDGWmi2rVWGlvtYyX5SuY5UDhS_9YSKPGBHuAJls/edit', descricao: 'Resumo do fluxo: Campanhas, buscar "mf", duplicar, ajustar e agendar.', obs: '' },
  { id: 'tutoriais-internos', grupo: 'Integração e treinamento', nome: 'Pasta: tutoriais dos processos internos', url: 'https://drive.google.com/drive/folders/1dsIN-zs1TVMwzFhd4tVmTKquUAGMyT36', descricao: 'Vídeos da Érica: e-mail no Active, tags, Zoom, termo de imagem, limpar StreamYard, subir Zoom no YouTube.', obs: '' },
  { id: 'banner-email', grupo: 'Integração e treinamento', nome: 'Banner padrão dos e-mails da Mentoria', url: 'https://drive.google.com/file/d/1U0i6cXdvH7Rzb3UQWFOLyGDKpT5aGX7x/view', descricao: 'Imagem padrão para os e-mails da Mentoria Fluxo.', obs: '' },
  { id: 'respostas-padrao', grupo: 'Integração e treinamento', nome: 'Respostas padrão dos navs (doc)', url: 'https://docs.google.com/document/d/15qy9449nfZ9sIkEOb-a7Zi9UPtVZ0H_HO7BxlRCEPGo/edit?tab=t.0', descricao: 'Respostas padrão usadas pelo time de navegação, inclusive sobre agentes GPT.', obs: 'Compartilhado com o suporte em 09/2025.' },

  /* ---------- Canais do Slack ---------- */
  { id: 'sl-navs-info', grupo: 'Canais do Slack', nome: '#fluxo-infos-navegadores', url: 'https://readytogohq.slack.com/archives/C054NGUNQ8Y', descricao: 'Informações que os navegadores vão consultar depois: eventos, regras, links, resumos do Lázaro.', obs: 'Só o essencial, sem caixa alta e com pouco emoji.' },
  { id: 'sl-time-rtg', grupo: 'Canais do Slack', nome: '#fluxo-time-rtg', url: 'https://readytogohq.slack.com/archives/C02RD5VEEAW', descricao: 'Comunicação do dia a dia com os navegadores.', obs: '' },
  { id: 'sl-ia', grupo: 'Canais do Slack', nome: '#fluxo-ia', url: 'https://readytogohq.slack.com/archives/C0B2PKGMD41', descricao: 'IA e automações: NavMaster, Severino, skills, ideias de projeto, bugs.', obs: 'Toda mensagem sobre IA e agentes vai aqui, não no canal de comunicados do no-code (Darah, 31/08/2026).' },
  { id: 'sl-eventos', grupo: 'Canais do Slack', nome: '#fluxo-evento-e-entregáveis', url: 'https://readytogohq.slack.com/archives/C08SVPNBBU6', descricao: 'Time de Eventos e Entregáveis: planejamento, definições, retrôs.', obs: '' },
  { id: 'sl-evento-flp', grupo: 'Canais do Slack', nome: '#evento-flp', url: 'https://readytogohq.slack.com/archives/C0B6NC3PVQU', descricao: 'Escala e alinhamentos dos navegadores durante o evento (só temas dos naves).', obs: 'Renomeado a cada pico.' },
  { id: 'sl-links', grupo: 'Canais do Slack', nome: '#fluxo-links-analises', url: 'https://readytogohq.slack.com/archives/C0B6CUW2FPB', descricao: 'Relatórios da automação de links das análises (sucessos, falhas, bloqueios).', obs: '' },
  { id: 'sl-grupos', grupo: 'Canais do Slack', nome: '#aprovação-grupos-abertos', url: 'https://readytogohq.slack.com/archives/C0BENKEUP36', descricao: 'Relatórios do robô de aprovação e remoção nos grupos do WhatsApp.', obs: '' },
  { id: 'sl-diag', grupo: 'Canais do Slack', nome: '#fluxo-diagnósticos', url: 'https://readytogohq.slack.com/archives/C0AHTR9H6P3', descricao: 'Analisadores: planos de ação, fechamento de análises, trechos de prova.', obs: '' },
  { id: 'sl-fin', grupo: 'Canais do Slack', nome: '#fluxo-duvidas-financeiro', url: 'https://readytogohq.slack.com/archives/C09NADR5H18', descricao: 'Inadimplência, reativação de acesso, competência das análises (Lya).', obs: '' },
  { id: 'sl-rel', grupo: 'Canais do Slack', nome: '#fluxo-duvidas-relacionamento', url: 'https://readytogohq.slack.com/archives/C0AEKB30A4R', descricao: 'Demandas para o relacionamento, congelamento e cancelamento.', obs: '' },
  { id: 'sl-comercial', grupo: 'Canais do Slack', nome: '#fluxo-comercial-duvidas', url: 'https://readytogohq.slack.com/archives/C04RGTS3DLG', descricao: 'Ponte com o comercial: integração, cases, dúvidas de lead, agenda das integrações (Robson), leads para o João Pedro.', obs: 'Dúvida de sócio passa primeiro por aqui.' },
  { id: 'sl-pos-venda', grupo: 'Canais do Slack', nome: '#pos-venda-fluxo-duvidas', url: 'https://readytogohq.slack.com/archives/C0BSA7M3TSN', descricao: 'Relacionamento e pós-venda acionam o time do Fluxo em dúvidas técnicas de alunos (gravação do SPP com IA, Tráfego com IA Pro); cancelamentos que chegam ao relacionamento geral.', obs: 'Criado em 24/08/2026 como #relacionamento-fluxo-duvidas; renomeado em 29/09. Padrão: [TÍTULO], contexto, dados.' },
  { id: 'sl-nocode', grupo: 'Canais do Slack', nome: '#nocode-comunicados-fluxer', url: 'https://readytogohq.slack.com/archives/C076LNLJ0NR', descricao: 'Comunicados do time de no-code sobre atualizações e erros do Fluxer.', obs: 'Só comunicados do no-code; dúvida de IA vai no #fluxo-ia.' },
  { id: 'sl-lab', grupo: 'Canais do Slack', nome: '#fluxer-lab-e-nave-master', url: 'https://readytogohq.slack.com/archives/C0B103NUPU4', descricao: 'Sugestões, melhorias e atualizações do Fluxer Lab e do Nave Master.', obs: '' },
  { id: 'sl-recados', grupo: 'Canais do Slack', nome: '#rtg-recados-gerais', url: 'https://readytogohq.slack.com/archives/C03R2UYHAQN', descricao: 'Recados para toda a empresa.', obs: '' },

  /* ---------- Ferramentas ---------- */
  { id: 'terminus', grupo: 'Ferramentas', nome: 'Terminus (links curtos)', url: 'https://app.terminusapp.com/', descricao: 'Cria os links vtsd.com.br/... e troca a URL de destino sem mudar o link divulgado.', obs: 'Login no 1Password; nossos links ficam no projeto do Fluxo. Sempre usar etiquetas para identificar objetivo e destino de cada link (ex.: "zoom-duvida" para os Zooms de sábado; clonar e trocar o destino).' },
  { id: 'active', grupo: 'Ferramentas', nome: 'ActiveCampaign (e-mails)', url: 'https://www.activecampaign.com/login', descricao: 'Disparo de e-mails de aviso para os mentorados (duplicar um e-mail existente).', obs: 'Login no 1Password. A newsletter está pausada por decisão da Fernanda (29/09/2026); ficam só os e-mails de avisos.' },
  { id: 'tally', grupo: 'Ferramentas', nome: 'Tally (formulários)', url: 'https://tally.so/', descricao: 'Formulários de feedback e inscrição; sempre duplicar um pronto.', obs: 'Código de login chega no e-mail do Fluxo.' },
  { id: 'zoom', grupo: 'Ferramentas', nome: 'Zoom (contas RTG)', url: 'https://us06web.zoom.us/', descricao: 'Contas do Zoom usadas nas entregas (Conta 3 para zooms diários; Conta 6 usada no Analisador Day).', obs: 'Gravação sempre na nuvem; backup e limpeza quase diários.' },
  { id: 'hotmart', grupo: 'Ferramentas', nome: 'Hotmart', url: 'https://app.hotmart.com/', descricao: 'Pagamentos, parcelas, cancelamentos e acesso aos cursos bônus.', obs: 'Consultas para navs: Lya e Érica (financeiro) e Robson (relacionamento; Tassia em licença-maternidade). Acesso ao Arsenal Viral e Criativo: Ester (Érica ou Lívia na ausência dela).' },
  { id: 'monday', grupo: 'Ferramentas', nome: 'Monday', url: 'https://venda-todo-santo-dia.monday.com/', descricao: 'Quadros da mentoria (links, contratos de renovação).', obs: '' },
  { id: 'claude', grupo: 'Ferramentas', nome: 'Claude', url: 'https://claude.ai/', descricao: 'IA usada pelo time para skills, análises e projetos; a conta da empresa tem limite mensal de tokens.', obs: '' },
  { id: 'streamyard', grupo: 'Ferramentas', nome: 'StreamYard', url: 'https://streamyard.com/', descricao: 'Transmissões das análises (links criados pela automação).', obs: '' }
];
